name: Docker image build and push

on: push  # Triggers the workflow on every push event

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "bhavesh188" --password-stdin

      - name: Build Docker Image
        run: docker build -t bhavesh188/my-fastapi-app:latest .

      - name: Push Docker Image
        run: docker push bhavesh188/my-fastapi-app:latest